#################
# UseGDCM.cmake #
#################

FIND_PATH(GDCM_DIR install-release/include/gdcm-1.2/gdcm.h HINTS "${PROJECT_SOURCE_DIR}/libraries/gdcm-1.2.5")
FIND_PATH(GDCM_INCLUDE_DIR gdcm-1.2/gdcm.h HINTS "${GDCM_DIR}/install-release/include")
INCLUDE_DIRECTORIES(${GDCM_INCLUDE_DIR})

SET(GDCM_LIBRARY_DIR_DEBUG "${GDCM_DIR}/install-debug/lib")
SET(GDCM_LIBRARY_DIR_RELEASE "${GDCM_DIR}/install-release/lib")

FIND_LIBRARY(GDCM_LIBRARY_DEBUG gdcm HINTS "${GDCM_LIBRARY_DIR_DEBUG}")
FIND_LIBRARY(GDCM_JPEG8_LIBRARY_DEBUG gdcmjpeg8 HINTS "${GDCM_LIBRARY_DIR_DEBUG}")
FIND_LIBRARY(GDCM_JPEG12_LIBRARY_DEBUG gdcmjpeg12 HINTS "${GDCM_LIBRARY_DIR_DEBUG}")
FIND_LIBRARY(GDCM_JPEG16_LIBRARY_DEBUG gdcmjpeg16 HINTS "${GDCM_LIBRARY_DIR_DEBUG}")

FIND_LIBRARY(GDCM_LIBRARY_RELEASE gdcm HINTS "${GDCM_LIBRARY_DIR_RELEASE}")
FIND_LIBRARY(GDCM_JPEG8_LIBRARY_RELEASE gdcmjpeg8 HINTS "${GDCM_LIBRARY_DIR_RELEASE}")
FIND_LIBRARY(GDCM_JPEG12_LIBRARY_RELEASE gdcmjpeg12 HINTS "${GDCM_LIBRARY_DIR_RELEASE}")
FIND_LIBRARY(GDCM_JPEG16_LIBRARY_RELEASE gdcmjpeg16 HINTS "${GDCM_LIBRARY_DIR_RELEASE}")

SET(GDCM_LIBRARY debug ${GDCM_LIBRARY_DEBUG} optimized ${GDCM_LIBRARY_RELEASE})
SET(GDCM_JPEG8_LIBRARY debug ${GDCM_JPEG8_LIBRARY_DEBUG} optimized ${GDCM_JPEG8_LIBRARY_RELEASE})
SET(GDCM_JPEG12_LIBRARY debug ${GDCM_JPEG12_LIBRARY_DEBUG} optimized ${GDCM_JPEG12_LIBRARY_RELEASE})
SET(GDCM_JPEG16_LIBRARY debug ${GDCM_JPEG16_LIBRARY_DEBUG} optimized ${GDCM_JPEG16_LIBRARY_RELEASE})
