#################
# UseGDCM.cmake #
#################

FIND_PATH(GDCM_DIR installed/include/gdcm-1.2/gdcm.h HINTS "${PROJECT_SOURCE_DIR}/libraries/gdcm-1.2.5")
FIND_PATH(GDCM_INCLUDE_DIR gdcm-1.2/gdcm.h HINTS "${GDCM_DIR}/installed/include")
INCLUDE_DIRECTORIES(${GDCM_INCLUDE_DIR})

SET(GDCM_LIBRARY_DIR "${GDCM_DIR}/installed/lib")
FIND_LIBRARY(GDCM_LIBRARY gdcm HINTS "${GDCM_LIBRARY_DIR}")
FIND_LIBRARY(GDCM_JPEG8_LIBRARY gdcmjpeg8 HINTS "${GDCM_LIBRARY_DIR}")
FIND_LIBRARY(GDCM_JPEG12_LIBRARY gdcmjpeg12 HINTS "${GDCM_LIBRARY_DIR}")
FIND_LIBRARY(GDCM_JPEG16_LIBRARY gdcmjpeg16 HINTS "${GDCM_LIBRARY_DIR}")
